### ISSUE TITLE
Add functions to dynamically load/unload plugins

### ISSUE THREAD

**Issue by Pheubel** [alliedmodders/sourcemod#1546]
At the current point in time Sourcemod does not have a neat way of dynamically loading/unloading plugins out of the box. There are currently some workarounds to emulate the behavior, for example: `InsertServerCommand("sm plugins load plugin.smx)` followed by `ServerExecute()`, after which the handle can be looked up with FindPluginByFile(pluginFile) or by iterating over the loaded plugins.

### API proposal
```c
// Attempts to load a plugin at the given path. Returns the handle for the plugin if loaded successfully or if the plugin was loaded previously, returns INVALID_HANDLE if plugin can't be found or loaded.
Handle LoadPlugin(const char[] filename);

// Attempts to unload the plugin referenced by the given handle.
void UnloadPlugin(Handle plugin);
```

When multiple plugins need to be loaded at once, the following API's could allow cleaner code.
```c
// Attempts to load multiple plugins and puts the handles in the buffer.
void LoadPlugins(const char[][] filenames, Handle[] pluginBuffer, int size);

// Attempts to unload the plugins referenced by the handles
void UnloadPlugins(Handle[] plugins, int size);
```

The runtime behavior of the functions would ensure that plugins are loaded/unloaded before continuing the execution in a script.

### Use case
An example use case would be in a plugin like the VSH2/FF2 bridge, where the ability plugins are loaded and unloaded on demand. [(code example)](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/modules/ff2/subplugins.sp)

another example similar to the one above, i am loading in plugins dynamically, then i am looking up their handles and finally i am registering ability forwards to specific functions. [(code)](https://github.com/Pheubel/VSH2Bosses/blob/master/src/ConfigBoss.sp#L633)

**Comment by asherkin** [comment]
Generally the design of SM pushes *against* this - the expectation is that SM is left to load all desired plugins in dependency order, they stay loaded, and only do things when desired. Plugins that are designed to be dependencies should offer functionality for their dependents to use, not control them - and there has frequently been a lot of push back against specific plugins "thinking they know best" and trying to interfere with other unrelated plugins.

I fear that adding an interface to unload an arbitrary other plugin fails against once of the core principles of good API design, which is that "good" actions should be easy and obvious, and "bad" actions should be difficult and obscure. Mid-game plugin loading has similar pain points as it is not a cheap operation, today there is JIT compilation of the pcode and static verification of methods, in the future it is expected that it could be full compilation from source - you really don't want that to be happening mid-game outside of development.

VSH/FF2 were very explicitly designed to create their own ecosystem and ignore the norms of SM, I think it's going to take some convincing that the direction they went in is objectively better and that the norms of SM should be adapted to make life easier for them, rather than that their design was just flawed from the beginning. Other large modular plugins do not seem to suffer from the same pain points, so I don't think it is a fundamental design issue.

I would expect the subplugins here to call a native provided by the core to register themselves, passing in a set of functions to be called as the main lifecycle callbacks (as private forwards owned by the core). The core plugin then decides what forwards to invoke when, which is routes the behaviour to the correct subplugin - rather than relying on global forwards and having the right subplugins currently loaded.

**Comment by dvander** [comment]
The reason for the SM design was simple: server operators should choose which plugins they're running. Not a sub-plugin that could download other plugins and start activating them.

Ability plugins (micro-plugins?) should be loaded all the time and used as needed. The resource cost is extremely low.
