### ISSUE TITLE
m_hViewModel breaking old plugins

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [alliedmodders/sourcemod#1701]
L 01/23/2022 - 06:00:12: [SM] Call stack trace:
L 01/23/2022 - 06:00:12: [SM]   [0] GetEntDataEnt2
L 01/23/2022 - 06:00:12: [SM]   [1] Line 496, deathmatch/players.sp::players_Timer_FastSwitch
L 01/23/2022 - 06:00:12: [SM] Exception reported: Offset 0 is invalid
L 01/23/2022 - 06:00:12: [SM] Blaming: deathmatch.smx

Code:
https://forums.alliedmods.net/showpost.php?p=2645164&postcount=2473

`asherkin — Today at 20:30
there are a few 1.11 builds where accessing m_hViewModel doesn't work

[20:31]
it is an array, which SM previously didn't understand, so there was a window of time where full array prop support was a work in progress where accessing it as a non-array broke but accessing it as an array wasn't implemented yet

[20:35]
ah, actually that one will be broken in current SM 1.11, it's because FindSendPropOffs is wrong (which is why it was deprecated an eon ago and replaced with FindSendPropInfo)

[20:36]
FindSendPropOffs returns the local offset from the parent rather than the offset from the entity, but the parent in this case is now the array container (now that SM can see that it exists) (edited)

[20:36]
so the local offset is correctly 0

[20:36]
Note, this function may return offsets that do not work!
If a property is nested beneath a parent object, the resulting offset will be invalid for direct use with data functions.  Therefore, you should use FindSendPropInfo() instead.  An example of such a property is CTFPlayer::DT_LocalPlayer.m_nDisguiseClass on Team Fortress.`

**Comment by asherkin** [comment]
I think this should just be a case of adding something like the following to `FindSendPropOffs` to maintain bcompat here:

```cpp
// Before we added support for DPT_Array props, FindInSendTable would have given us the inner array prop itself.
// To maintain compatibility with older plugins still using us, pluck out the inner array prop ourselves.
if (pSend->GetType() == DPT_Array && pSend->GetArrayProp()) {
    return pSend->GetArrayProp()->GetOffset();
}
```

This should be sane as 1) I'm pretty sure it could have never hit here for `DPT_Array` props before anyway (we were previously always matching the identically named inner prop, which is before it in the sendtable and 2) the outer array prop's local offset is always 0 (which is why this old code is now getting 0 back).

`FindSendPropOffs` was deprecated a long time ago for exactly this problem, but it is still present in a number of old plugins and `m_hViewModel` is fairly common to touch, so I think it is worth the backwards compatibility shim before stable 1.11.
