### ISSUE TITLE
[Bug Report] Sigscans are broken on Windows 

### ISSUE THREAD

**Issue by StShAzzy** [alliedmodders/sourcemod#2134]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Win10 22H2
  * Game/AppID (with version if applicable): 440
  * Current SourceMod version: 1.12.0.7101
  * Current SourceMod snapshot: 7101:80ad76a5
  * Current Metamod: Source snapshot: 1.11.0-dev+1148V
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

SDKTools Sigscans are failing
L 04/18/2024 - 20:38:30: [SDKTOOLS] Sigscan for FireOutput failed
L 04/18/2024 - 20:56:32: [TF2] Sigscan for SetInWaitingForPlayers failed

**Comment by khalik38** [comment]
Do we have a fix for this?

L 04/19/2024 - 17:19:51: SourceMod error session started
L 04/19/2024 - 17:19:51: Info (map "cp_dustbowl") (file "C:\xxx\xxx\tf\addons\sourcemod\logs\errors_20240419.log")
L 04/19/2024 - 17:19:51: [SDKTOOLS] Sigscan for FireOutput failed
L 04/19/2024 - 17:19:51: [TF2] Sigscan for SetInWaitingForPlayers failed
L 04/19/2024 - 17:19:51: [TF2] No Gameplay Rules detours could be initialized - Disabled Gameplay Rules functions
L 04/19/2024 - 17:19:51: [TF2] Sigscan for SetInWaitingForPlayers failed
L 04/19/2024 - 17:19:51: [TF2] No Gameplay Rules detours could be initialized - Disabled Gameplay Rules functions
L 04/19/2024 - 17:19:51: [TF2] Sigscan for SetInWaitingForPlayers failed
L 04/19/2024 - 17:19:51: [TF2] No Gameplay Rules detours could be initialized - Disabled Gameplay Rules functions
L 04/19/2024 - 17:19:51: [TF2] Sigscan for SetInWaitingForPlayers failed


**Since the update, this is broken - any fix ?**
Running server on Windows

**Comment by StShAzzy** [comment]
not only that, but several other problems too, for instance
L 04/19/2024 - 16:29:49: [SM] Exception reported: Failed to locate function
L 04/19/2024 - 16:29:49: [SM] Blaming: TF2_PhysicsGun.smx
L 04/19/2024 - 16:29:49: [SM] Call stack trace:
L 04/19/2024 - 16:29:49: [SM]   [0] TF2_RegeneratePlayer
L 04/19/2024 - 16:29:49: [SM]   [1] Line 246, /home/xxx/code/sm/github/TF2_PhysicsGun/addons/sourcemod/scripting/TF2_PhysicsGun.sp::Event_PlayerSpawn
L 04/19/2024 - 16:29:49: [SM] Exception reported: Failed to locate function
L 04/19/2024 - 16:29:49: [SM] Blaming: TF2_PhysicsGun.smx
L 04/19/2024 - 16:29:49: [SM] Call stack trace:
L 04/19/2024 - 16:29:49: [SM]   [0] TF2_RegeneratePlayer
L 04/19/2024 - 16:29:49: [SM]   [1] Line 246, /home/xxx/code/sm/github/TF2_PhysicsGun/addons/sourcemod/scripting/TF2_PhysicsGun.sp::Event_PlayerSpawn
L 04/19/2024 - 16:29:49: [SM]   [3] TF2_RespawnPlayer
L 04/19/2024 - 16:29:49: [SM]   [4] Line 339, C:\Users\xxx\Documents\GitHub\baguko-plugins\plugins\tf2-reverts\scripting\reverts.sp::OnGameFrame
L 04/19/2024 - 16:29:49: World triggered "Round_Start"
L 04/19/2024 - 16:29:49: [SM] Exception reported: Failed to locate function
L 04/19/2024 - 16:29:49: [SM] Blaming: TF2_PhysicsGun.smx
L 04/19/2024 - 16:29:49: [SM] Call stack trace:
L 04/19/2024 - 16:29:49: [SM]   [0] TF2_RegeneratePlayer
L 04/19/2024 - 16:29:49: [SM]   [1] Line 246, /home/xxx/code/sm/github/TF2_PhysicsGun/addons/sourcemod/scripting/TF2_PhysicsGun.sp::Event_PlayerSpawn
L 04/19/2024 - 16:29:57: [SM] Exception reported: Failed to locate function
L 04/19/2024 - 16:29:57: [SM] Blaming: TF2_PhysicsGun.smx
L 04/19/2024 - 16:29:57: [SM] Call stack trace:
L 04/19/2024 - 16:29:57: [SM]   [0] TF2_RegeneratePlayer
L 04/19/2024 - 16:29:57: [SM]   [1] Line 246, /home/xxx/code/sm/github/TF2_PhysicsGun/addons/sourcemod/scripting/TF2_PhysicsGun.sp::Event_PlayerSpawn
L 04/19/2024 - 16:29:57: [SM]   [3] TF2_RespawnPlayer
L 04/19/2024 - 16:29:57: [SM]   [4] Line 34, svb-commands/respawn.sp::Command_Respawn

**Comment by fearts** [comment]
https://github.com/alliedmodders/sourcemod/commit/d426d1f04f336db433ec873000817ebbba391be1
