### ISSUE TITLE
[Help Wanted] How do I get TF2 Offsets? (Specifically "GiveNamedItem")

### ISSUE THREAD

**Issue by Latepoo** [alliedmodders/sourcemod#2182]
I'm trying to run a server with a plugin that needs _TF2Items_ to run. When I launch the server it just gets stuck on this line of code indefinitely: 
![image](https://github.com/alliedmodders/sourcemod/assets/83547931/8eca0523-06a6-42b6-99c0-0c29024b7172)
From my agonizing almost **6 hour research** trying to fix this I've concluded that the _"GiveNamedItem"_ offset is outdated and I don't know what to do in order to get the newest one. If someone has or knows how to get this offset it would be greatly appreciated. Thank you.
Just to be clear I want to update this, its the key to ending my headache:
![image](https://github.com/alliedmodders/sourcemod/assets/83547931/6c8e8640-bf08-4313-8526-48f2c55e11a8)

**Comment by Mikusch** [comment]
These offsets are actually correct for the current version of the game, so I doubt TF2Items is the cause of this freeze. You should try removing/moving other third-party extensions or plugins to try and narrow it down.

**Comment by NotnHeavy** [comment]
For what it's worth, TF2Items automatically updates its offsets as far as I'm aware, so it doesn't typically require any maintenance.

**Comment by Kenzzer** [comment]
Please follow the [Issue Template](https://github.com/alliedmodders/sourcemod/blob/master/.github/ISSUE_TEMPLATE.md), secondly the problem you're creating a github issue for doesn't seem connected to sourcemod. It seems more likely to be a problem with a third-party extension. Try opening a forum thread on alliedmodders, or join the discord for more help, the nature of your issue seems like it will require a lot of back forth which isn't suitable in github issues.
