### ISSUE TITLE
Add .editorconfig for Resharper C++ 2017 users

### ISSUE THREAD

**Issue by WildCard65** [alliedmodders/sourcemod#620]
Visual Studio 2017 has Roslyn support .editorconfigs, but currently, it only applies to C#, Resharper is a paid extension for Visual Studio that has a C++ version of it, it also supports .editorconfig as well as extends it, it may be helpful for contributors who use Resharper to stay within SM's coding style.

References:
https://www.jetbrains.com/help/resharper/2017.1/EditorConfig_CPP_CppBlankLinesPageScheme.html
https://www.jetbrains.com/help/resharper/2017.1/EditorConfig_CPP_CppBracesPageScheme.html
https://www.jetbrains.com/help/resharper/2017.1/EditorConfig_CPP_CppIndentStylePageSchema.html
https://www.jetbrains.com/help/resharper/2017.1/EditorConfig_CPP_CppOtherPageScheme.html
https://www.jetbrains.com/help/resharper/2017.1/EditorConfig_CPP_CppSpacesPageScheme.html
https://www.jetbrains.com/help/resharper/2017.1/EditorConfig_CPP_CppWrappingPageScheme.html

**Comment by psychonic** [comment]
editorconfig isn't exclusive to Resharper, but also exists separately as a free extension.

However, I don't think this makes sense since there is no consistent style to SM's code. Style is usually, mostly consistent within any individual files, but not always across files. It's a side effect of not having a strictly defined style guide with enforcement, and a larger number of individual contributors.

Otherwise, not a bad idea.

**Comment by WildCard65** [comment]
Resharper has it's own format file feature, if Resharper comes across an .editorconfig file, it was change it's settings (temporarly) to match the rules set in the file.
