### ISSUE TITLE
[CS:GO] KeyValues clamp to int32's max value 

### ISSUE THREAD

**Issue by shavitush** [alliedmodders/sourcemod#643]
When using `kv.GetString()` from KeyValues in CS:GO, if the string happens to be a number, it'll be clamped to 2147483647. Adding a letter to anywhere in the string inside the KeyValues avoids the 2147483647 clamping.

To test, use "3000000000" as a string to read from KeyValues with `kv.GetString()`. The string output will be "2147483647".

CS:S is fine. Haven't tested other games. Tested on both Windows and Linux. Latest Steam versions of CS:S and CS:GO.

Versions:

```
meta version
Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/4a27e2f
Build ID: 959:4a27e2f
Loaded As: Valve Server Plugin
Compiled on: Apr 26 2017
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/

sm version
SourceMod Version Information:
    SourceMod Version: 1.8.0.6015
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6015)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Jul  6 2017 12:16:00
    Built from: https://github.com/alliedmodders/sourcemod/commit/b94620e
    Build ID: 6015:b94620e

```

**Comment by Benoist3012** [comment]
Same issue already happened in the past:
https://forums.alliedmods.net/showthread.php?t=293895

**Comment by psychonic** [comment]
When you use KeyValues, you opt into all of their behavior, including interpretation of integers like you mention. While we technically use our own implementation per base, it's still based on the game's implementation, and works as closely to it as possible, which is why you don't see the issue on CS:S.

If you want full control over the data, use a different data structure. A similar one for on disk would be SMC, or for in-memory, a StringMap.

**Comment by shavitush** [comment]
Thanks @psychonic - I'll report the issue to Valve instead!
