### ISSUE TITLE
Regenerate, Respawn, ForceWeaponChange Causing Random Crashes

### ISSUE THREAD

**Issue by fearts** [alliedmodders/sourcemod#736]
https://crash.limetech.org/stats/8b1194e975ff3014051e70ff4dcf515b5e214bbb726a43ebf3c109e63bc6a8f54788fc932d1f684d

^This seem to be happening to multiple server owners over different mods. I have seen it happen in FF2/VSH/Randomizer/WarioWare.

A crash seem to occur randomly on round start or when people are spawned in for the randomizer/wario server. I've not been able to recreate the crash because it seems to happen once a day and has be impossible to track for me.

https://forums.alliedmods.net/showthread.php?t=302264&page=3

Some other people have posted here about it.^

I talked to many people about this issue and no one seems to understand what is happening. I'm not sure if this is the right place to address this issue. I don't think it's my codes fault as many others seem to be getting this issue but I could be wrong. I don't know if it's something Sourcemod needs to fix/update or if Valve just messed with things and they need to update on their end. If anyone is able to give any additional information to help debug/fix this issue it would be very helpful. I hate coming here to bother you guys about this but it has basically been happening since the Inferno TF2 update. (Also I'm running Windows OS)

EDIT:

Some new information I got from a friend is if too many people are respawned and regenerated it causes a instant server crash.

**Comment by asherkin** [comment]
This isn’t an issue in SourceMod and Valve’s opinion is that something is being done while the player is in a bad state.

Somebody or multiple somebodies need to do the debugging work to find the root cause of the crash so we can understand what is going wrong inside the game - then maybe SourceMod can be changed to work around the issue or at least throw an error rather than crashing.

As it stands, the only option we have to stop this crash is to remove the functionality from SourceMod, since the problem is not on our side.
