### ISSUE TITLE
`sm exts list` displays wrong numbers with failed optional extensions

### ISSUE THREAD

**Issue by asherkin** [alliedmodders/sourcemod#737]
Ran into a couple of issues with #728, filing this as a reminder as the fix has turned out to be more complicated than what I originally dived in to fix and I have to head out.

1. The numbers printed are disjoint across the two lists, but need to calculated beforehand when pushing to the separate lists - as they are used in other commands (`sm exts info` `sm exts unload`) to index into the global list.
2. The optional list is titled "not found" but really it is "not loaded", which can be caused by many conditions other than non-existence.
3. The load error message isn't being included.

2. and 3. are trivial, and helped along by the fact we have sane error messages on Windows again in 1.9 like `File not found` rather than `0000007e`.

For 1. I think the easiest fix would be to make the `required` and `options` lists of `struct { int num; CExtension *ext; }` and calculate the `num` in the initial iteration of `m_Libs`.

Before you open an issue please review the contributing guidelines for this repository.

**Comment by Drifter321** [comment]
Didnt even think about the numbers being used elsewhere oops. sm reload would be another case I think in which case having two number 1's for example is gonna be impossible to know which the user meant. All I can think of is displaying the internal number (and having the list all screwed up) or replacing the <FAILED> tag with something else for optional instead of a separate list (like my initial change)

**Comment by KyleSanderson** [comment]
It looks like everything is kosher again?
