### ISSUE TITLE
Prevent declaring a dynamic-sized string with a literal

### ISSUE THREAD

**Issue by nosoop** [alliedmodders/sourcemod#760]
This compiles (tested as of latest dev branch), but produces unexpected results:
```
#pragma semicolon 1
#include <sourcemod>

#pragma newdecls required

public void OnPluginStart() {
	// disregard the redundant code warning
	if (false) {
		char sample_text[] = "unreachable";
		PrintToServer("%s (should be unreachable)", sample_text);
	} else {
		char[] sample_text2 = "else";
		PrintToServer("%s (should be else)", sample_text2);
	}
}
```
This outputs "unreachable (should be else)".  I spent an embarrassingly long time trying to figure out why it was using the wrong string, along with various other weird behaviors.

Attempting to use a string literal in a non-fixed char array declaration should probably throw a compile-time error.

**Comment by Headline** [comment]
This looks to me like a sourcepawn bug, perhaps you should recreate this issue on the [sp project page](http://github.com/alliedmodders/sourcepawn)

**Comment by asherkin** [comment]
We’re happy to take SP issues in either, it’s its easier and cleaner than
trying to move them.

On 28 Jan 2018, at 09:14, nosoop <notifications@github.com> wrote:

This compiles (tested as of latest dev branch), but produces unexpected
results:

#pragma semicolon 1
#include <sourcemod>

#pragma newdecls required

public void OnPluginStart() {
	// disregard the redundant code warning
	if (false) {
		char sample_text[] = "unreachable";
		PrintToServer("%s (should be unreachable)", sample_text);
	} else {
		char[] sample_text2 = "else";
		PrintToServer("%s (should be else)", sample_text2);
	}
}

This outputs "unreachable (should be else)". I spent an embarrassingly long
time trying to figure out why it was using the wrong string, along with
various other weird behaviors.

Attempting to use a string literal in a non-fixed char array declaration
should probably throw a compile-time error.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alliedmodders/sourcemod/issues/760>, or mute the thread
