### ISSUE TITLE
SourceMod 1.9.0 Build 6226 doesn't read SteamID3 correctly when adding Admins for SQL

### ISSUE THREAD

**Issue by rautamiekka** [alliedmodders/sourcemod#776]
Regardless of the double quotes around a SID3, like `"[U:1:38465345]"`, `sm_sql_addadmin` thinks the first number is the password and the second number is the immunity level, creating incorrect SQL row.

Output:
```
] rcon sm_sql_addadmin "JulmaD[essu]" "steam" "[U:1:38465345]" ""
[SM] Administrator successfully added to the database.
```

In contrast `sm_sql_setadmingroups "steam" "[U:1:38465345]" "Admin"` prints
```
] rcon sm_sql_setadmingroups "steam" "[U:1:38465345]" "Admin"
[SM] Could not find group: ":"
[SM] Could not find group: "1"
[SM] Could not find group: ":"
[SM] Could not find group: "38465345]"
[SM] Successfully added one group to the given administrator.
```
but still successfully assigns the group in the SQL.

**Comment by Fyren** [comment]
I can run your commands fine directly on the server console.  I think the issue is that the quotes you provide in your rcon command don't survive and so what the server actually gets is `sm_sql_setadmingroups steam [U:1:38465345] Admin` and, unfortunately, can't work.  Using rcon, your first command is probably actually creating a user with `[U` for the identity.
