### ISSUE TITLE
Feature request: Add OnClientDisconnect parameter

### ISSUE THREAD

**Issue by Ilusion9** [alliedmodders/sourcemod#859]
- What is your end goal, or what are you trying to accomplish?

`void OnClientDisconnect(int client, bool mapchange)`

- Why is this necessary, or what benefit do you see with it?

To hook the disconnects by map changes.
And maybe it can be developed as int reason with defines (by client, by map or dropped by server).

- Will this be useful to others?

Yes.

And some question: does server crash fire this event?

**Comment by asherkin** [comment]
I don’t think we want to expose this, and I’m not sure we know. It is an intentional design descision that from SourceMod’s perspective clients disconnect and a new set of clients connect after a map change. If you want to know if a client has really disconnected you should listen to the player_disconnect event instead.

No, no code will execute once the process has crashed.

**Comment by KyleSanderson** [comment]
Asher is right. Use OnMapEnd() if this is desired.
