### ISSUE TITLE
SQL_CheckConfig always returns true (dev)

### ISSUE THREAD

**Issue by TotallyMehis** [alliedmodders/sourcemod#865]
```
 SourceMod Version Information:
    SourceMod Version: 1.10.0.6322
    SourcePawn Engine: 1.10.0.6322, jit-x86 (build 1.10.0.6322)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: Aug  2 2018 14:34:15
    Built from: https://github.com/alliedmodders/sourcemod/commit/3511d2a4
    Build ID: 6322:3511d2a4
    http://www.sourcemod.net/
```

```
#include <sourcemod>
#include <dbi>

public void OnPluginStart()
{
    SetFailState( "Result: %i", SQL_CheckConfig( "idontexist" ) ); // Result: 1
}
```

**Comment by asherkin** [comment]
This is because you have the "default" connection configured, so it is falling back to it (as `Database.Connect` is expected to).

https://mxr.alliedmods.net/sourcemod/source/core/logic/Database.cpp#313

I'm not sure what I would expect `SQL_CheckConfig` to do in this case - what are you trying to use it for?

**Comment by TotallyMehis** [comment]
`Returns if a named configuration is present in databases.cfg.`

This makes the function pointless + changes behavior.
Simply googling `"SQL_CheckConfig"` you can see a ton of plugins relying on it and how it's used.

**Comment by Headline** [comment]
Yeah this is a side-effect from #791, where we assured that default will always be the fallback to clean up other areas. Didn't realize SQL_CheckConfig used this, thanks for the report 👍

**Comment by asherkin** [comment]
Yes, we know what the documentation says - the question was what are **you** trying to use `SQL_CheckConfig` for? What are you trying to get out of checking "if a named configuration is present in databases.cfg"?

**Comment by asherkin** [comment]
I had a look through most of the uses of `SQL_CheckConfig` indexed by GitHub, and almost all of them are either:
```
if (SQL_CheckConfig("database")) {
    SQL_TConnect(SQL_OnConnect, "database");
} else {
    ThrowError("Database configuration not configured");
}
```

Which is fine, as that is exactly the behaviour change that was intended in #791 here - `SQL_TConnect` will fall back to "default", so `SQL_CheckConfig` should match it's behaviour.

Or like this:
```
if (SQL_CheckConfig("database")) {
    SQL_TConnect(SQL_OnConnect, "database");
} else if (SQL_CheckConfig("default")) {
    SQL_TConnect(SQL_OnConnect, "default");
} else {
    ThrowError("Database configuration not configured");
}
```

Which is again fine, and the intention of the behaviour change in #791 was to avoid every plugin having to implement this fallback to "default" separately - as very few do.

One interesting outlier is https://github.com/sahapro33/ArmyRanks/blob/e07c6dd1fa8e7570492f0fcc52bf6b973e162e67/scripting/army/events/OnConfigsExecuted.sp#L4, which wants to fallback to a local SQLite DB hardcoded in the plugin. `SQLite_UseDatabase` is probably on the chopping block alongside `SQL_ConnectCustom`, so I'm not to worried about this one and it still isn't broken by the change here.

I think the options here are either:
1) Update the documentation to match the current behaviour post-#791, and make sure SM isn't trying to use "default" if it hasn't been configured at all, or
2) Rollback the fallback-to-"default" change completely (I kinda lean towards this one, but the former is probably better in the long run with proper documentation and user education.)

**Comment by KyleSanderson** [comment]
Option three, add a strict bool and default it to false. This should make everyone happy?

**Comment by Headline** [comment]
@KyleSanderson I do like this idea, that way a plugin author can opt into the default fallback behavior. 

@asherkin thoughts?

**Comment by CrazyHackGUT** [comment]
We need a strict bool as suggested @KyleSanderson. More plugins switches on SQLite, if MySQL configuration doesn't exists.
By example: `[Shop] Core` by FrozDark and `[VIP] Core` by R1KO.
https://github.com/FD-Forks/Shop-Core/blob/7d4834d23034a3b86caded43c5ca61a65fdd5d86/addons/sourcemod/scripting/shop/db.sp#L204-L216
https://github.com/R1KO/VIP-Core/blob/11bb1fec61e0d9ab2ab388c5011d1de7e5000d35/addons/sourcemod/scripting/vip/Database.sp#L23-L33

**Comment by CrazyHackGUT** [comment]
Also `default` section exists in SourceMod by default, and points to MySQL on `localhost`. So this new feature breaks all compability with old plugins guaranteed. Very many users don't edit this `default` configuration. I don't edited this configuration too, because i create manually connections for all plugins to different databases.

**P.S.**: You should have thought about this before starting to implement.

**Comment by CrazyHackGUT** [comment]
That's true. I created issue, as you said.

**Comment by peace-maker** [comment]
The default `databases.cfg` ships with 
https://github.com/alliedmodders/sourcemod/blob/2cc22778b5a24d1659199ff475d55156dbab048d/configs/databases.cfg#L3-L22

and I hardly ever hear of people actually using that default all-in-one connection.

I don't see how `SQL_TConnect` is falling back to `"default"` if the requested section doesn't exist.

```sourcepawn
public void OnPluginStart()
{
	if (SQL_CheckConfig("mydb"))
		Database.Connect(SQL_OnConnected, "mydb");
}
public void SQL_OnConnected(Database db, const char[] error, any data)
{
	if (!db)
	{
		LogError("Failed to connect to database: %s", error);
		return;
	}
	// g_hDB = db;
}
```

That plugin logs `Failed to connect to database: Could not find database config "mydb"` using the stock databases.cfg.
```
sm version
 SourceMod Version Information:
    SourceMod Version: 1.10.0.6329
    SourcePawn Engine: 1.10.0.6329, jit-x86 (build 1.10.0.6329)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: Aug 19 2018 04:44:42
    Built from: https://github.com/alliedmodders/sourcemod/commit/caf09142
    Build ID: 6329:caf09142
    http://www.sourcemod.net/
```

I'd make sure the fallback to `"default"` is behind an optional param defaulting to `false` if you really want to force people to care about the `"default"` section. The native is more useful for telling if a database configuration _actually_ exists instead of if the DBI would connect to something.

**Comment by kice** [comment]
If "default" config was set and all API will fall back to it, then what's the point of adding the function "SQL_CheckConfig"?

BTW, it looks like not all SQL connect API will fall back to "default",

```
if (SQL_CheckConfig("something")) {
    Database.Connect(SQL_OnConnect, "something");
} else {
    Database.Connect(SQL_OnConnect, "default");
}
```

**Comment by Headline** [comment]
@kice we're simply restoring old behavior here. `Database.Connect` doesn't fall back to default, so in the current 1.10 master the SQL_CheckConfig will return true, and then the code will fail on Database.Connect when `"something"` doesn't exist.

**Comment by ttasdasda** [comment]
Just updated to SM 1.10:
>09/24/2018 - 10:00:59: [admin-sql-threaded.smx] Failed to connect to database: Could not find database config "admins"

I don't have an "admins" config, and admin-sql-threaded hasn't changed since 1.9, it uses
`	if (SQL_CheckConfig("admins"))
	{
		Database.Connect(OnDatabaseConnect, "admins", ConnectLock);
	} else {
		Database.Connect(OnDatabaseConnect, "default", ConnectLock);
	}`
So no, it doesn't seem to fall back to default by itself.
